#!/usr/bin/env node
'use strict';

// Cold-start resync: rebuild .planning/graph/delivery-state.json|yaml from the
// ACTUAL GitHub state (gh CLI). The local state file is a cache; GitHub is the
// source of truth. Idempotent — safe to run at every /shipyard:deliver start.
//
// Ticket status model:
//   merged   — a PR for the ticket branch is merged
//   pr-open  — PR exists and is open (checks/review detail attached)
//   pending  — no PR and no branch on the remote yet
//   branched — branch exists on remote but no PR yet

const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');

const ROOT = process.cwd();
const GRAPH_DIR = path.join(ROOT, '.planning', 'graph');
const TICKETS = path.join(GRAPH_DIR, 'tickets.json');

function fail(msg) {
  console.error(`state-sync: ${msg}`);
  process.exit(1);
}

function gh(args) {
  try {
    return execFileSync('gh', args, { encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] });
  } catch (e) {
    fail(`gh ${args.join(' ')} failed: ${e.stderr ? String(e.stderr).trim() : e.message}`);
  }
}

if (!fs.existsSync(TICKETS)) fail('missing .planning/graph/tickets.json — run validate-graph first');
const { tickets } = JSON.parse(fs.readFileSync(TICKETS, 'utf8'));

// one call: every PR whose head branch starts with ticket/
const prs = JSON.parse(
  gh(['pr', 'list', '--state', 'all', '--limit', '200',
      '--json', 'number,state,isDraft,headRefName,mergedAt,url,reviewDecision'])
);
const byBranch = {};
for (const pr of prs) byBranch[pr.headRefName] = pr;

const remoteBranches = new Set(
  gh(['api', 'repos/{owner}/{repo}/branches', '--paginate', '--jq', '.[].name'])
    .split('\n').filter(Boolean)
);

const state = {};
for (const [id, t] of Object.entries(tickets)) {
  const pr = byBranch[t.branch];
  const entry = { branch: t.branch, pr: pr ? pr.number : null, status: 'pending' };
  if (pr) {
    if (pr.state === 'MERGED') {
      entry.status = 'merged';
    } else if (pr.state === 'OPEN') {
      entry.status = 'pr-open';
      entry.draft = pr.isDraft;
      entry.review_decision = pr.reviewDecision || null;
      entry.url = pr.url;
      const checks = JSON.parse(
        gh(['pr', 'checks', String(pr.number), '--json', 'name,state'])
      );
      entry.checks = {
        total: checks.length,
        failing: checks.filter((c) => ['FAILURE', 'ERROR', 'CANCELLED', 'TIMED_OUT'].includes(c.state)).length,
        pending: checks.filter((c) => ['PENDING', 'QUEUED', 'IN_PROGRESS', 'EXPECTED'].includes(c.state)).length,
      };
    } else {
      entry.status = 'pending'; // closed unmerged PR -> ticket back to pending
      entry.note = `PR #${pr.number} closed without merge`;
    }
  } else if (remoteBranches.has(t.branch)) {
    entry.status = 'branched';
  }
  state[id] = entry;
}

// derived readiness: every dependency merged
for (const [id, t] of Object.entries(tickets)) {
  if (state[id].status === 'pending') {
    const blockers = t.depends_on.filter((d) => state[d] && state[d].status !== 'merged');
    state[id].ready = blockers.length === 0;
    if (blockers.length) state[id].blocked_by = blockers;
  }
}

fs.mkdirSync(GRAPH_DIR, { recursive: true });
fs.writeFileSync(path.join(GRAPH_DIR, 'delivery-state.json'), JSON.stringify(state, null, 2) + '\n');

const yaml = ['# generated by state-sync.cjs from live GitHub state — do not edit'];
for (const [id, s] of Object.entries(state)) {
  yaml.push(`${id}:`);
  for (const [k, v] of Object.entries(s)) {
    yaml.push(`  ${k}: ${typeof v === 'object' && v !== null ? JSON.stringify(v) : v}`);
  }
}
fs.writeFileSync(path.join(GRAPH_DIR, 'delivery-state.yaml'), yaml.join('\n') + '\n');

// board summary on stdout for the /shipyard:deliver skill
const buckets = {};
for (const [id, s] of Object.entries(state)) {
  const b = s.status === 'pending' ? (s.ready ? 'ready' : 'blocked') : s.status;
  (buckets[b] ??= []).push(id);
}
for (const b of ['ready', 'blocked', 'branched', 'pr-open', 'merged']) {
  if (buckets[b]) console.log(`${b}: ${buckets[b].join(', ')}`);
}
console.log('wrote .planning/graph/delivery-state.json and delivery-state.yaml');
